protected/modules/admin/controllers/AccountsController.php
<?php

class AccountsController extends Controller
{
    public function actionIndex()
    {
        $this->render('index');
    }

    public function actionList()
    {
        $limit = intval(Yii::app()->request->getParam('limit', 10));
        $page = intval(Yii::app()->request->getParam('page', 1));
        $sid = Yii::app()->request->getParam('sid');
        $uid = Yii::app()->request->getParam('uid');
        $skip = ($page-1)*$limit;
        $params=array(
            'skip'=>$skip, 
            'count'=>$limit,
        );
        if($sid){
            $params['sid']=$sid;
        }
        if($uid){
            $params['uid']=$uid;
        }
        if($sid || $uid){
            $result = ApiUtil::api('account/search', $params);
        }else{
            $result = ApiUtil::api('account/list', $params);
        }

        $this->renderJSON($result);
    }

    public function actionDelete()
    {
        $uid = Yii::app()->request->getParam('uid');
        $sid = Yii::app()->request->getParam('sid');

        if($uid)
        {
            $params = array('uid'=>$uid);
        }else{
            $params = array('sid'=>$sid);
        }

        if(Yii::app()->request->isPostRequest)
        {
            $result = ApiUtil::api('account/delete', $params);

            $this->renderJSON($result);
        }
        else
            throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
    }

    public function actionLog()
    {
        $uid = Yii::app()->request->getParam('uid');
        $sid = Yii::app()->request->getParam('sid');

        $limit = intval(Yii::app()->request->getParam('limit', 10));
        $page = intval(Yii::app()->request->getParam('page', 1));
        $skip = ($page-1)*$limit;
        $params=array(
            'skip'=>$skip, 
            'count'=>$limit,
        );
        if($uid)
        {
            $params['uid'] = $uid;
        }else{
            $params['sid'] = $sid;
        }
        $result = ApiUtil::api('account/log', $params);

        $this->renderJSON($result);
    }

    public function actionLock()
    {
        $uid = Yii::app()->request->getParam('uid');
        $sid = Yii::app()->request->getParam('sid');

        if($uid)
        {
            $params = array('uid'=>$uid);
        }else{
            $params = array('sid'=>$sid);
        }
        $result = ApiUtil::api('account/lock', $params);

        $this->renderJSON($result);
    }

    public function actionUnLock()
    {
        $uid = Yii::app()->request->getParam('uid');
        $sid = Yii::app()->request->getParam('sid');

        if($uid)
        {
            $params = array('uid'=>$uid);
        }else{
            $params = array('sid'=>$sid);
        }
        $result = ApiUtil::api('account/unlock', $params);

        $this->renderJSON($result);
    }

}

protected/modules/admin/controllers/AdsController.php
<?php

class AdsController extends Controller
{
	public function actionCreate()
	{
		$model=new AdForm();
		if(isset($_POST['AdForm']))
		{
			$model->attributes=$_POST['AdForm'];
			if($model->validate())
			{
				$user = Yii::app()->user;
				$model->creator = $user->id;
				if($model->create()){
					Yii::app()->user->setFlash('success', '创建成功');

					$this->redirect(array('index'));
				}
				Yii::app()->user->setFlash('error', '创建失败');
			}
		}
		$this->render('create',array('model'=>$model));
	}

	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			$result = ApiUtil::api('ad/delete', array('id'=>$id));

			$this->renderJSON($result);
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	public function actionIndex()
	{
		$model=new AdForm();
		$this->render('index', array(
			'model'=>$model
		));
	}

	public function actionList()
	{
		$limit = intval(Yii::app()->request->getParam('limit', 10));
		$page = intval(Yii::app()->request->getParam('page', 1));
		$skip = ($page-1)*$limit;
		$params=array(
			'skip'=>$skip, 
			'count'=>$limit
		);

		$result = ApiUtil::api('ad/list', $params);

		$this->renderJSON($result);
	}

	public function actionUpdate($id)
	{
		$model=new AdForm();
		if(isset($_POST))
		{
			$model->attributes=$_POST;
			$model->id = $id;
			if($model->validate())
			{
				if($model->update()){
					$this->renderJSON(array(
						'code'=>0
					));
				}
				$this->renderJSON(array(
					'code'=>500
				));
			}

			$this->renderJSON(array(
				'code'=>500
			));
		}
	}
}

protected/modules/admin/controllers/CountriesController.php
<?php

class CountriesController extends Controller
{
	public function actionIndex()
	{
		$this->render('index');
	}

	public function actionList()
	{
		$result = ApiUtil::api('country/list');

		if($result['code']==0){
			$countries = array();
			foreach ($result['list'] as $key => $value) {
				$countries[] = array(
					'id'=>$key,
					'name'=>$value
				);
			}
			$result['list'] = $countries;
		}

		$this->renderJSON($result);
	}

	public function actionMap()
	{
		$result = ApiUtil::api('country/list');
		$this->renderJSON($result);
	}

	public function actionDelete()
	{
		$id = Yii::app()->request->getParam('id');
		if(Yii::app()->request->isPostRequest && $id)
		{
			$result = ApiUtil::api('country/list');

			$list = $result['list'];

			if(isset($list[$id])){
				unset($list[$id]);
				$result = ApiUtil::api('country/update', array('country_list'=>json_encode($list)));
			}

			$this->renderJSON($result);
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	public function actionCreate()
	{
		$model=new CountryForm();
		if(isset($_POST['CountryForm']))
		{
			$model->attributes=$_POST['CountryForm'];
			if($model->validate())
			{
				if($model->create()){
					Yii::app()->user->setFlash('success', '创建成功');

					$this->redirect(array('index'));
				}
				Yii::app()->user->setFlash('error', '创建失败');
			}
		}
		$this->render('create',array('model'=>$model));
	}
}

protected/modules/admin/controllers/OrdersController.php
<?php

class OrdersController extends Controller
{
	public function actionCreate()
	{
		$this->render('create');
	}

	public function actionIndex()
	{
		$this->render('index');
	}

	public function actionList()
	{
		$uid = Yii::app()->request->getParam('uid', '');
		$orderid = Yii::app()->request->getParam('orderid', '');
		$beg = Yii::app()->request->getParam('beg', '20000101000000');
		$end = Yii::app()->request->getParam('end', '20501230000000');
		$params=array(
		);

		if($beg){
	        $beg = strtotime($beg);
	        $beg = strftime('%Y%m%d%H%M%S', $beg);
	        $params['beg'] = $beg;
		}
		if($end){
	        $end = strtotime($end);
	        $end = strftime('%Y%m%d%H%M%S', $end);
	        $params['end'] = $end;
		}
		if($uid){
			$params['uid'] = $uid;
		}
		if($orderid){
			$params['orderid'] = $orderid;
		}

		$result = ApiUtil::api('order/list4admin', $params);

		$this->renderJSON($result);
	}

	public function actionStat()
	{
		$this->render('stat');
	}

	public function actionStatList()
	{
		$country = Yii::app()->request->getParam('country', '');
		$orderid = Yii::app()->request->getParam('orderid', '');
		$beg = Yii::app()->request->getParam('beg', '20000101000000');
		$end = Yii::app()->request->getParam('end', '20501230000000');
		$export = Yii::app()->request->getParam('export', false);
		$params=array(
		);

		if($beg){
	        $beg = strtotime($beg);
	        $beg = strftime('%Y%m%d%H%M%S', $beg);
	        $params['beg'] = $beg;
		}
		if($end){
	        $end = strtotime($end);
	        $end = strftime('%Y%m%d%H%M%S', $end);
	        $params['end'] = $end;
		}
		if($country){
			$params['country'] = $country;
		}

		$result = ApiUtil::api('order/stat', $params);
		if($export && $result['list']){
			$this->exportArray($result['list']);
		}

		$this->renderJSON($result);
	}
}

protected/modules/admin/views/layouts/main.php
<!doctype html>
<html ng-app="myApp">
<head>
    <meta charset="utf-8"/>
    <meta name="language" content="en" />
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ng-grid.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/admin.css" />
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/javascripts/lib/json3.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/javascripts/lib/angular.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/javascripts/lib/ng-grid-2.0.7.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/javascripts/app.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/javascripts/common.js"></script>
</head>
<body class="container" ng-app="myApp" id="ng-app">
    <div class="row">
        <div class="span3 left_side">
            <div class="logo">
                <img src="/images/logo_igogo.png">
            </div>
            <div class="menus">
                <ul>
                    <?php if(Yii::app()->user->getState('user_level')==1){ ?>
                    <li class="menu">
                        <?php echo CHtml::link('帐号管理', array('admins/index'), array('class'=>'icon_account')); ?>
                    </li>
                    <?php } ?>
                    <?php if(Yii::app()->user->getState('user_level')<=2){ ?>
                    <li class="menu">
                        <?php echo CHtml::link('广告管理', array('ads/index'), array('class'=>'icon_advertisement')); ?>
                    </li>
                    <li class="menu">
                        <?php echo CHtml::link('最新分享', array('shares/index'), array('class'=>'icon_share')); ?>
                    </li>
                    <li class="menu">
                        <?php echo CHtml::link('最新旅游', array('posts/index'), array('class'=>'icon_travel')); ?>
                    </li>
                    <li class="menu">
                        <?php echo CHtml::link('商品管理', array('productPackages/index'), array('class'=>'icon_product')); ?>
                    </li>
                    <li class="menu">
                        <?php echo CHtml::link('订单查询', array('orders/index'), array('class'=>'icon_order')); ?>
                    </li>
                    <?php } ?>
                    <li class="menu">
                        <?php echo CHtml::link('查账', array('orders/stat'), array('class'=>'icon_audit')); ?>
                    </li>
                    <?php if(Yii::app()->user->getState('user_level')<=2){ ?>
                    <li class="menu">
                        <?php echo CHtml::link('国家列表管理', array('countries/index'), array('class'=>'icon_country')); ?>
                    </li>
                    <li class="menu">
                        <?php echo CHtml::link('用户账户管理', array('accounts/index')); ?>
                    </li>
                    <li class="menu">
                        <?php echo CHtml::link('意见反馈', array('feedbacks/index')); ?>
                    </li>
                    <?php } ?>
                </ul>
            </div>
        </div>                 
        <div class="span9 right_side">
            <div class="header">
                <?php echo CHtml::link('首页', array('/admin/'), array('class'=>'home')); ?>

                <div class="dropdown pull-right my_info">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php echo Yii::app()->user->name; ?><span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><?php echo CHtml::link('注销', array('/site/logout')) ?></li>
                    </ul>
                </div>
            </div>

            <div class="content">
                <?php if(Yii::app()->user->hasFlash('error')):?>
                    <div class="alert alert-error">
                        <?php echo Yii::app()->user->getFlash('error'); ?>
                    </div>
                <?php endif; ?>
                <?php if(Yii::app()->user->hasFlash('success')):?>
                    <div class="alert alert-success">
                        <?php echo Yii::app()->user->getFlash('success'); ?>
                    </div>
                <?php endif; ?>
                <?php echo $content; ?>
            </div>
        </div>
    </div>
</body>
</html>